<?php
$l['number'] 						= 'Numer faktury';
$l['date'] 							= 'Data wystawienia';
$l['due'] 							= 'Tremin płatności';
$l['to'] 							= 'Klient';
$l['from'] 							= 'Sprzedawca';
$l['product'] 						= 'Produkt';
$l['amount'] 						= 'ILOŚĆ';
$l['price'] 						= 'Cena';
$l['discount'] 						= 'Rabat';
$l['vat'] 							= 'VAT';
$l['total'] 						= 'Razem';
$l['page'] 							= 'Strona';
$l['page_of'] 						= 'z';
